/* Autogenerated by /home/kurt/Sources/linuxcnc-dev/bin/halcompile on Thu Oct  5 17:15:20 2017 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:mpg:4 axis MPG");
MODULE_INFO(linuxcnc, "descr:4 axis MPG with 4 selectable user defined jog scales. Multiplexed to require 4 total input pins for axis and scale selections.");
MODULE_INFO(linuxcnc, "notes:Switches should be multiplexed with two diodes so that the outputs are as follows:\n\nPosition 1: out0=0 out1=0\nPosition 2: out0=1 out1=0\nPosition 3: out0=0 out1=1\nPosition 4: out0=1 out1=1\n\nWhere out0 and out1 are conected to axis0 and axis1, or scale0 and scale1, as the case may be.");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:Kurt Jacobson");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "pin:axis0:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:axis1:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:scale0:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:scale1:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "param:mpg_scale1:float:0:rw::.01:None");
MODULE_INFO(linuxcnc, "param:mpg_scale2:float:0:rw::.001:None");
MODULE_INFO(linuxcnc, "param:mpg_scale3:float:0:rw::.0001:None");
MODULE_INFO(linuxcnc, "param:mpg_scale4:float:0:rw::.00001:None");
MODULE_INFO(linuxcnc, "param:mpg_pulses:float:0:rw::4:None");
MODULE_INFO(linuxcnc, "pin:enable_x:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:enable_y:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:enable_z:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:enable_a:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:mpg_scale:float:0:out::None:None");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *axis0;
    hal_bit_t *axis1;
    hal_bit_t *scale0;
    hal_bit_t *scale1;
    hal_bit_t *enable_x;
    hal_bit_t *enable_y;
    hal_bit_t *enable_z;
    hal_bit_t *enable_a;
    hal_float_t *mpg_scale;
    hal_float_t mpg_scale1;
    hal_float_t mpg_scale2;
    hal_float_t mpg_scale3;
    hal_float_t mpg_scale4;
    hal_float_t mpg_pulses;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_IN, &(inst->axis0), comp_id,
        "%s.axis0", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->axis1), comp_id,
        "%s.axis1", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->scale0), comp_id,
        "%s.scale0", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->scale1), comp_id,
        "%s.scale1", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->enable_x), comp_id,
        "%s.enable-x", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->enable_y), comp_id,
        "%s.enable-y", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->enable_z), comp_id,
        "%s.enable-z", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->enable_a), comp_id,
        "%s.enable-a", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->mpg_scale), comp_id,
        "%s.mpg-scale", prefix);
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->mpg_scale1), comp_id,
        "%s.mpg-scale1", prefix);
    inst->mpg_scale1 = .01;
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->mpg_scale2), comp_id,
        "%s.mpg-scale2", prefix);
    inst->mpg_scale2 = .001;
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->mpg_scale3), comp_id,
        "%s.mpg-scale3", prefix);
    inst->mpg_scale3 = .0001;
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->mpg_scale4), comp_id,
        "%s.mpg-scale4", prefix);
    inst->mpg_scale4 = .00001;
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->mpg_pulses), comp_id,
        "%s.mpg-pulses", prefix);
    inst->mpg_pulses = 4;
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
RTAPI_MP_INT(count, "number of mpg");
RTAPI_MP_ARRAY_STRING(names, 16, "names of mpg");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("mpg");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "mpg.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef axis0
#define axis0 (0+*__comp_inst->axis0)
#undef axis1
#define axis1 (0+*__comp_inst->axis1)
#undef scale0
#define scale0 (0+*__comp_inst->scale0)
#undef scale1
#define scale1 (0+*__comp_inst->scale1)
#undef enable_x
#define enable_x (*__comp_inst->enable_x)
#undef enable_y
#define enable_y (*__comp_inst->enable_y)
#undef enable_z
#define enable_z (*__comp_inst->enable_z)
#undef enable_a
#define enable_a (*__comp_inst->enable_a)
#undef mpg_scale
#define mpg_scale (*__comp_inst->mpg_scale)
#undef mpg_scale1
#define mpg_scale1 (__comp_inst->mpg_scale1)
#undef mpg_scale2
#define mpg_scale2 (__comp_inst->mpg_scale2)
#undef mpg_scale3
#define mpg_scale3 (__comp_inst->mpg_scale3)
#undef mpg_scale4
#define mpg_scale4 (__comp_inst->mpg_scale4)
#undef mpg_pulses
#define mpg_pulses (__comp_inst->mpg_pulses)


#line 43 "mpg.comp"
FUNCTION(_){
    //Demux axis selection
    if (!axis0 && !axis1) {
        enable_x = 1;
        enable_y = 0;
        enable_z = 0;
        enable_a = 0;
    } else if (axis0 && !axis1) {
        enable_x = 0;
        enable_y = 1;
        enable_z = 0;
        enable_a = 0;
    } else if (!axis0 && axis1) {
        enable_x = 0;
        enable_y = 0;
        enable_z = 1;
        enable_a = 0;
    } else if (axis0 && axis1) {
        enable_x = 0;
        enable_y = 0;
        enable_z = 0;
        enable_a = 1;
    }

    //Demux mpg scale selection
    if (!scale0 && !scale1) {
        mpg_scale = mpg_scale1/mpg_pulses;
    } else if (scale0 && !scale1) {
        mpg_scale = mpg_scale2/mpg_pulses;
    } else if (!scale0 && scale1) {
        mpg_scale = mpg_scale3/mpg_pulses;
    } else if (scale0 && scale1) {
        mpg_scale = mpg_scale4/mpg_pulses;
    }
}

static int __comp_get_data_size(void) { return 0; }
